// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.
package model

type NewCourse struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	CategoryID  string  `json:"categoryId"`
}

type NewCategory struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}
